# Generated by Django 5.1.1 on 2025-09-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_specialization_doctor_special_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
